# cluster-id
# - defines name of the cluster of servers that can communicate with each other, can be left default
cluster-id: "cluster0"

# server-id
# - unique identifier of this server, which will be part of the cluster (cluster-id)
server-id: "serverOne"

# packet-retrieve-interval
# - interval in ticks to send and retrieve data packets, setting this below 5 ticks is not recommended
packet-send-and-retrieve-interval: 5

# clear-old-packets
# - if the server should discard old packets that were sent when it was offline
clear-old-packets: true

# redis
# - redis connection details, this optional, but needed for the data packet functionality
redis:
  ip: '127.0.0.1'
  port: 123
  password: 'password'

# mysql-connections
# - define as many connections as you want
mysql-connections:
  global:
    url: jdbc:mysql://localhost:3306/database
    username: username
    password: password
  local:
    url: jdbc:mysql://localhost:3306/database
    username: username
    password: password