server-id: "serverOne"
server-id-list:
  - "serverOne"
  - "serverTwo"


mysql-connections:
  global:
    url: jdbc:mysql://localhost:3306/database
    username: username
    password: password
  local:
    url: jdbc:mysql://localhost:3306/database
    username: username
    password: password

redis:
  ip: '127.0.0.1'
  port: 123
  password: 'password'